### ISSUE TITLE
使用静态ipv6地址后缀而不是轮询

### ISSUE THREAD

**Issue by noblehng** [Archeb/ADDNS#1]
偶然看到来源的楼，懒得注册，就在这边写了。

如何访问路由后服务，ipv6和ipv4的解决思路是类似的，那楼里的48楼已经给出方法了。

具体点说就是给要提供服务的设备分配一个静态ipv6地址后缀。slaac就用eui-64或者启用privacy extension时对应的静态地址后缀；用dhcpv6就根据duid或mac来绑定（duid更标准），odhcpd可以设置相应的host节，dnsmasq也有相应的配置。

路由器防火墙ipv4要dnat，ipv6就是允许相应的转发，ip6tables就是filter表的FORWARD链，动态前缀就mask后缀。

ddns就是简单问题了，对ipv6支持好的直接支持识别动态前缀，支持不好的就自己拼完整地址。

**Comment by Archeb** [comment]
我...不是楼主哇
